# Generated by Django 4.2.4 on 2023-09-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_products', '0003_size_created_size_public_id_size_updated'),
        ('api_user', '0002_user_wishlist_alter_user_avatar_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='products_bought',
            field=models.ManyToManyField(blank=True, related_name='products_bought_by', to='api_products.product'),
        ),
    ]
