# Generated by Django 4.2.4 on 2023-08-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_author_alter_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='edited',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
