services:
  store-app:
    build:
      context: .
    ports:
      - "8080:8080"
    command: python manage.py runserver 0.0.0.0:8080
    container_name: store-app
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=store-db
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: store-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null
