# Generated by Django 4.2.4 on 2023-08-29 13:39

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_products', '0002_product_public_id_product_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='size',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
