# Generated by Django 4.2.4 on 2023-09-07 13:12

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_products', '0004_gallery_title_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='products_images'),
        ),
    ]
