# Generated by Django 4.2.4 on 2023-09-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_products', '0007_alter_productcategory_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
