# Generated by Django 4.2.4 on 2023-09-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_products', '0010_remove_productcategory_product_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
