# Generated by Django 4.2.4 on 2023-09-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_products', '0013_remove_brand_product_remove_productcategory_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
