# Generated by Django 4.2.4 on 2023-09-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_products', '0019_remove_brand_slug_remove_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='asd', max_length=130, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='asd', max_length=130, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default='asd', max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
