# Generated by Django 4.2.4 on 2023-08-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_product_cart_quantity_cart_size_delete_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='size',
            new_name='product_size',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
