# Generated by Django 4.2.4 on 2023-09-15 09:52

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amount_discount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=2,
                        validators=[django.core.validators.MaxValueValidator(99)],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
